### ISSUE TITLE
fatal error when mobile phone not stored

### ISSUE THREAD

**Issue by valentin3522** [thelia-modules/PayPlugModule#7]
when the client didn't give the mobile phone, there is a fatal error.

Need to add a "if mobilephone = NULL ..."

Fatal error: Uncaught TypeError: Argument 1 passed to PayPlugModule\Event\PayPlugPaymentEvent::setBillingMobilePhone() must be of the type string, null given,

**Comment by lopes-vincent** [comment]
Fixed by https://github.com/thelia-modules/PayPlugModule/commit/c889cecd68429b491f45fd2892962fc9b7b3cba7
